services:
  mlops-api:
    image: jimenaamr/mlops-api
    container_name: mlops-api
    ports:
      - "6000:5000"
    restart: always

  mlops-web:
    image: jimenaamr/mlops-web
    container_name: mlops-web
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://mlops-api:5000/predict
    depends_on:
      - mlops-api
    restart: always
