apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-web-deployment
  labels:
    app: mlops-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-web
  template:
    metadata:
      labels:
        app: mlops-web
    spec:
      containers:
        - name: mlops-web
          image: gcr.io/practicagke-476807/mlops-web:latest  # ← Ruta de imagen
          ports:
            - containerPort: 8501
          env:
            - name: API_URL
              value: http://mlops-api-service:6000/predict  # ← Conexión al servicio interno de la API
